### ISSUE TITLE
[BUG] Can’t download apps or refresh apps

### ISSUE THREAD

**Issue by IachiF7W** [SideStore/SideStore#652]
### Describe the bug

When I go to add and app or refresh an app it prompts me with “ Unable to connect to the device, make sure Wireguard is enabled and you're connected to WiFi”
![IMG_2154](https://github.com/SideStore/SideStore/assets/167112547/5d5d9f46-3e4c-4539-9404-891aba0bf1e9)

### Instructions to reproduce

1. Turn ON Wi-Fi
2. Turn ON WireGuard VPN
3. Open SideStore
4. Go to add an app or refresh
5. Press the button

### What version of SideStore are you using?

The newest one

**Comment by nevespt** [comment]
UP Vote

**Comment by TechnicallyJackson** [comment]
I fixed it. Make a new jitterbugpair file

**Comment by NsCrosu** [comment]
`SideJITServer --pair` will break the jitterbugpair file. Make a new one and repair.

**Comment by mclarence554** [comment]
I made a new jitterbugpairfile but sidestore still wont refresh for me

**Comment by Spidy123222** [comment]
Solution was told. Make new pairing file. I'll add that you should try restarting the vpn or app at times.
