### ISSUE TITLE
[BUG] Apps added via SideStore Repo not detecting new updates

### ISSUE THREAD

**Issue by jimmysofat6864** [SideStore/SideStore#975]
### Describe the bug

I have an app added with a source so it it supposed to be able to check for updates and prompt me to install them but for some reason, the updates don't show. 

### Instructions to reproduce

1. Install older version of an application that supports an altstore repo ex. uYouEnhanced, eevespotify, etc/ 
2. Prompt to update to latest app not visible 

![Image](https://github.com/user-attachments/assets/6dc8d464-e48d-4e7d-aa3f-b29aef8e84ee)
![Image](https://github.com/user-attachments/assets/9f7b99a2-8711-409b-8539-74ca83d34bec)
![Image](https://github.com/user-attachments/assets/eee66d06-9a5f-4200-b6bf-29baeee3331f)

### What version of SideStore are you using?

0.6.1

**Comment by danielepintore** [comment]
+1. I have the same issue. There is any way to force the update?

**Comment by Casuallynoted** [comment]
Beyond removing and reinstalling the app, sadly I don’t think there’s a way to manually force an update atm. I’m also having this issue.

**Comment by Aransh** [comment]
Seeing the same issue (with my own custom source).

Only solution I found currently is removing and re-adding the source, at that point SideStore stops recognizing the app is even installed from the source (which I would say is a bug of its own but that's a whole other story), allowing you to "install" it, which basically downloads the latest version and replaces the app in place with no data loss (practically same as upgrade).

Seems to me like a source management cache issue...

**Comment by Aransh** [comment]
Just to add more details as I suspect these are 2 different symptoms of the same root issue:

I released a new version for an app on my own source (self hosted locally with nginx, cache disabled server-side)

I have 2 devices using it:

iPad - did not detect the update no matter how much I refreshed, basically exact same issue described in this issue.
as I said, removing and re-adding the source allowed me to install the latest version

iPhone - detected the update, but upon trying to update, threw error "<app> could not be installed. The SHA-256 hash of <app> does not match the hash specified by the source."
I have verified 20 times and the hash on the source was definitely correct, and as same I stated above, removing and re-adding the source allowed me to install the latest version without SHA errors, raising my suspicion that this is a cache issue (was probably comparing to SHA of previous version)

**Comment by bebound** [comment]
Same issue occurs in the https://github.com/Balackburn/Apollo/ repository as well.
The altstore works as expected.
Related issue: https://github.com/Balackburn/Apollo/issues/90

**Comment by mahee96** [comment]
yeah there were some improvements in the update section to receive sidestore's own release channels like nightly, alpha etc, so some existing feature might have gotten broken,.

if one can produce a clear screen recording on what they expect and what they see in addition to the posted screenshots, we can look at it.

**Comment by bebound** [comment]
Not sure if this info helps.
I installed the apollo 1.15.11 with ImprovedCustomApi version 1.4.5.
```
"version": "1.15.11",
"buildVersion": "1.4.5",
```
After ImprovedCustomApi version 2.0.0 is released, I can see the new version in news tab, but not able to update to 2.0.0 like the PO.
```
"version": "1.15.11",
"buildVersion": "2.0.0",
```
Maybe sidestore can't handle the `buildVersion` update?
Repo source: https://github.com/Balackburn/Apollo/blob/main/apps_glass.json

**Comment by mahee96** [comment]
can u try again once, coz I think I fixed the hasUpdate or whatever is used for version checking within sidestore. 

if still persists, provide me a way to test this, ie show me the steps what u are doing to run into this.

**Comment by jimmysofat6864** [comment]
@bebound @Aransh @Casuallynoted @danielepintore 

Are you able to test this? Currently I am still trying to locate a repo where this is reproducible as the repo I was testing it with no longer exists and I am trying to find another one.

**Comment by mahee96** [comment]
probably fixed in latest nightly since we reworked some flows. check and let us know.

**Comment by az4521** [comment]
i installed the latest nightly, this isn't fixed

the app isn't shown as having an update if the only thing that has changed in the repo json is the buildVersion

**Comment by mahee96** [comment]
fthis must have been fixed by now if not then post the source used and what version was active and steps to reproduce exactly and detailed in a new issue.

closing this one
